name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: showtimes_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Setup PostgreSQL
        run: |
          sudo apt-get -y install libpq-dev
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Setup Database
        env:
          PGHOST: localhost
          PGUSER: postgres
          DATABASE_USERNAME: postgres
          RAILS_ENV: test
        run: |
          bin/rails db:setup
      - name: Rails Tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          DATABASE_USERNAME: postgres
          RAILS_ENV: test
        run: |
          bin/rails test
